//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIT310Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int CatID { get; set; }
        public string Breed { get; set; }
        public int PlayfullnessID { get; set; }
        public int ActivityLevelID { get; set; }
        public int ColorID { get; set; }
        public int PlayfullnessPlayfullnessID { get; set; }
        public int ColorColorID { get; set; }
    
        public virtual ActivityLevel ActivityLevel { get; set; }
        public virtual Playfullness Playfullness { get; set; }
        public virtual Color Color { get; set; }
    }
}
